const eventsDemoData = [
  {
    id: "1",
    type: "events",
    title: "Wedding Ceremony",
    category: "Celebration",
    date: "2026-05-30",
    time: "11:00",
    description: "Wedding ceremony of Emmanuel and Grace.",
    status: "upcoming",
  },
  {
    id: "10",
    type: "birthday",
    celebrant: "Morrison Samuel",
    date: "2026-06-02",
    time: "14:00",
    age: 28,
    description: "Birthday celebration for Morrison Samuel.",
    status: "upcoming",
  },
  {
    id: "2",
    type: "events",
    title: "Christmas Dinner",
    category: "Holiday",
    date: "2025-12-25",
    time: "18:00",
    description: "Annual Christmas family dinner.",
    status: "completed",
  },
  {
    id: "3",
    type: "events",
    title: "Convocation",
    category: "Education",
    date: "2025-06-21",
    time: "09:00",
    description: "Celebrating Sarah's graduation.",
    status: "completed",
  },
  {
    id: "4",
    type: "events",
    title: "Naming Ceremony",
    category: "Ceremony",
    date: "2026-07-14",
    time: "12:00",
    description: "Naming ceremony for Baby Daniel.",
    status: "upcoming",
  },
  {
    id: "5",
    type: "events",
    title: "Family Thanksgiving",
    category: "Religious",
    date: "2026-08-20",
    time: "09:30",
    description: "Annual thanksgiving service.",
    status: "upcoming",
  },
  {
    id: "6",
    type: "meeting",
    title: "Monthly Family Meeting",
    category: "General",
    date: "2026-05-24",
    time: "15:30",
    description: "Monthly family meeting.",
    status: "upcoming",
  },
  {
    id: "7",
    type: "meeting",
    title: "Executive Committee Meeting",
    category: "Executive",
    date: "2026-06-10",
    time: "17:00",
    description: "Discuss family development projects.",
    status: "upcoming",
  },
  {
    id: "8",
    type: "meeting",
    title: "Emergency Family Meeting",
    category: "Emergency",
    date: "2026-05-28",
    time: "19:30",
    description: "Discuss an urgent family matter.",
    status: "upcoming",
  },
  {
    id: "9",
    title: "Financial Planning Meeting",
    type: "meeting",
    category: "Finance",
    date: "2026-06-18",
    time: "16:00",
    description: "Review family savings and investments.",
    status: "scheduled",
  },

  {
    id: "11",
    type: "birthday",
    celebrant: "Grace Adibor",
    date: "2026-07-11",
    time: "13:00",
    age: 45,
    description: "Birthday celebration for Grace Adibor.",
    status: "upcoming",
  },
  {
    id: "12",
    celebrant: "Daniel Adibor",
    type: "birthday",
    date: "2026-08-09",
    time: "16:30",
    age: 8,
    description: "Daniel's 8th birthday party.",
    status: "upcoming",
  },
  {
    id: "13",
    celebrant: "John Adibor",
    type: "birthday",
    date: "2026-09-18",
    time: "18:00",
    age: 60,
    description: "60th birthday celebration.",
    status: "upcoming",
  },
  {
    id: "14",
    title: "Hospital Admission",
    type: "incident",
    category: "Health",
    reportedBy: "Morrison Samuel",
    date: "2026-05-18",
    time: "08:45",
    severity: "High",
    description: "Grandmother was admitted to the hospital.",
    status: "active",
  },
  {
    id: "15",
    title: "House Fire",
    type: "incident",
    category: "Emergency",
    reportedBy: "John Adibor",
    date: "2026-04-30",
    time: "22:15",
    severity: "Critical",
    description: "Minor fire outbreak. No casualties.",
    status: "resolved",
  },
  {
    id: "16",
    title: "Missing Family Document",
    type: "incident",
    category: "Security",
    reportedBy: "Grace Adibor",
    date: "2026-05-12",
    time: "10:20",
    severity: "Medium",
    description: "Original family land document reported missing.",
    status: "investigating",
  },
  {
    id: "17",
    title: "Medical Emergency",
    type: "incident",
    category: "Health",
    reportedBy: "Daniel Adibor",
    date: "2026-06-05",
    time: "07:50",
    severity: "Critical",
    description: "Emergency transport to the hospital.",
    status: "resolved",
  },
];


export default eventsDemoData;
